[build]
  # Install & build only inside your React/Vite folder
  command = "npm install --prefix welcomeweb && npm run build --prefix welcomeweb"
  # Publish the output from that folder
  publish = "welcomeweb/dist"
