[build]
  base   = "welcomeweb"       # ← CD into this folder first
  command = "npm install && npm run build"
  publish = "dist"            # ← in that folder, this will produce welcomeweb/dist

[dev]
  command = "npm start"
